// AUTO-GENERATED by planctl v2, do not edit
// Source: src/features/tasks/zsx//task_list.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Task = @import("../models/task.zig").Task;

/// Full task list. Returned by every handler (list / create / toggle
/// / delete) so the morph swaps `#content` in-place after each
/// mutation — no client-side state, server is the source of truth.
pub const TaskList = struct {
    tasks: []const Task,

    pub fn render(self: TaskList, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 12 "src/features/tasks/zsx//task_list.zsx"
        try out.appendSlice(allocator, "<div id=\"content\" class=\"space-y-4\">");
    try out.appendSlice(allocator, "<header class=\"flex items-center justify-between\">");
    try out.appendSlice(allocator, "<h1 class=\"text-2xl font-bold text-slate-800\">");
    try out.appendSlice(allocator, "Tasks");
    try out.appendSlice(allocator, "</h1>");
    try out.appendSlice(allocator, "<span class=\"text-xs text-slate-500\">");
    try appendValue(out, allocator, self.tasks.len);
    try out.appendSlice(allocator, "total");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</header>");
    try out.appendSlice(allocator, "<form data-on:submit__prevent=\"@post('/tasks', {contentType: 'json', payload: {Title: $newTitle}})\" class=\"flex gap-2\" data-signals=\"{newTitle: ''}\">");
    try out.appendSlice(allocator, "<input data-bind=\"newTitle\" placeholder=\"What needs doing?\" class=\"flex-1 px-3 py-2 rounded-md border border-slate-200 text-sm\" />");
    try out.appendSlice(allocator, "<button class=\"px-4 py-2 rounded-md bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium\">");
    try out.appendSlice(allocator, "Add");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</form>");
    if (self.tasks.len == 0) {
    try out.appendSlice(allocator, "<p class=\"text-slate-400 text-sm text-center py-12\">");
    try out.appendSlice(allocator, "No tasks yet — add one above.");
    try out.appendSlice(allocator, "</p>");
    } else {
    try out.appendSlice(allocator, "<ul class=\"bg-white rounded-xl border border-slate-200 divide-y divide-slate-100 shadow-sm\">");
    for (self.tasks) |t| {
    try out.appendSlice(allocator, "<li class=\"px-4 py-3 flex items-center gap-3\">");
    try out.appendSlice(allocator, "<button data-on:click=\"@put('/tasks/");
    try appendValue(out, allocator, t.TaskID);
    try out.appendSlice(allocator, "', {contentType: 'json', payload: {Done: ");
    try appendValue(out, allocator, t.toggleTo());
    try out.appendSlice(allocator, "}})\" class=\"w-5 h-5 rounded border-2 flex items-center justify-center ");
    try appendValue(out, allocator, t.boxClass());
    try out.appendSlice(allocator, "\">");
    try appendValue(out, allocator, t.checkMark());
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "<span class=\"flex-1 text-sm ");
    try appendValue(out, allocator, t.titleClass());
    try out.appendSlice(allocator, "\">");
    try appendValue(out, allocator, t.Title);
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<button data-on:click=\"@delete('/tasks/");
    try appendValue(out, allocator, t.TaskID);
    try out.appendSlice(allocator, "')\" class=\"text-slate-300 hover:text-red-500\">");
    try out.appendSlice(allocator, "🗑");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</li>");
    }
    try out.appendSlice(allocator, "</ul>");
    }
    try out.appendSlice(allocator, "</div>");

// #line 49 "src/features/tasks/zsx//task_list.zsx"

    }
};

