const std = @import("std");
const Compiler = @import("zsx").Compiler;

const alloc = std.heap.page_allocator;

fn compile(src: []const u8) !struct { code: []u8, has_errors: bool } {
    var compiler = Compiler.init(alloc, src, "test.zsx", .zig);
    const result = try compiler.compile();
    return .{ .code = result.code, .has_errors = result.has_errors };
}

fn expectContains(haystack: []const u8, needle: []const u8) !void {
    if (std.mem.indexOf(u8, haystack, needle) == null) {
        std.debug.print("Expected to find:\n  \"{s}\"\nin output\n", .{needle});
        return error.TestExpectedEqual;
    }
}

fn expectNotContains(haystack: []const u8, needle: []const u8) !void {
    if (std.mem.indexOf(u8, haystack, needle) != null) {
        std.debug.print("Expected NOT to find:\n  \"{s}\"\nin output\n", .{needle});
        return error.TestExpectedEqual;
    }
}


test "compiler: output starts with AUTO-GENERATED header" {
    const result = try compile("const x = 42;\n");
    defer alloc.free(result.code);
    try expectContains(result.code, "// AUTO-GENERATED by planctl");
}

test "compiler: header has std and web imports" {
    const result = try compile("const x = 42;\n");
    defer alloc.free(result.code);
    try expectContains(result.code, "const std = @import(\"std\");");
    try expectContains(result.code, "const web = @import(\"web\");");
}

test "compiler: header has appendValue helper" {
    const result = try compile("const x = 42;\n");
    defer alloc.free(result.code);
    try expectContains(result.code, "fn appendValue");
    try expectContains(result.code, "web.appendEscaped");
}


test "compiler: strips const std = @import(\"std\")" {
    const src = "const std = @import(\"std\");\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    const count = std.mem.count(u8, result.code, "const std = @import(\"std\")");
    try std.testing.expectEqual(@as(usize, 1), count);
}

test "compiler: strips @import(\"web\")" {
    const src = "const web = @import(\"web\");\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    const count = std.mem.count(u8, result.code, "const web = @import(\"web\")");
    try std.testing.expectEqual(@as(usize, 1), count);
}

test "compiler: strips _ = allocator;" {
    const src = "_ = allocator;\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectNotContains(result.code, "_ = allocator;");
}

test "compiler: strips //! doc comments" {
    const src = "//! Module doc comment\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectNotContains(result.code, "//! Module doc comment");
}

test "compiler: strips pub const std = @import(\"std\")" {
    const src = "pub const std = @import(\"std\");\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectNotContains(result.code, "pub const std");
}

test "compiler: strips import with extra spaces" {
    const src = "const  std  =  @import( \"std\" );\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectNotContains(result.code, "const  std");
}

test "compiler: strips import with no spaces around =" {
    const src = "const std=@import(\"std\");\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectNotContains(result.code, "const std=");
}

test "compiler: strips pub const web import" {
    const src = "pub const web = @import(\"web\");\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectNotContains(result.code, "pub const web");
}

test "compiler: strips web_runtime import" {
    const src = "const rt = @import(\"web_runtime\");\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectNotContains(result.code, "const rt");
}

test "compiler: strips const Node = @import(\"web\").Node" {
    const src = "const Node = @import(\"web\");\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectNotContains(result.code, "const Node = @import");
}

test "compiler: does not strip unrelated imports" {
    const src = "const foo = @import(\"bar\");\nconst x = 42;\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "const foo = @import(\"bar\")");
}


test "compiler: full  with JSX" {
    const src =
        \\pub fn render(self: @This()) !Node {
        \\    return (
        \\        <div class="page">
        \\            <h1>{self.title}</h1>
        \\        </div>
        \\    );
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try std.testing.expect(!result.has_errors);
    try expectContains(result.code, "out.appendSlice(allocator, \"<div");
    try expectContains(result.code, "out.appendSlice(allocator, \"<h1>\")");
    try expectContains(result.code, "appendValue(out, allocator, self.title)");
}


test "compiler: function without allocator param gets one added" {
    const src =
        \\pub fn render(self: @This()) !Node {
        \\    return (
        \\        <div />
        \\    );
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "allocator: std.mem.Allocator");
}

test "compiler: function with existing allocator param is left alone" {
    const src =
        \\pub fn render(self: @This(), allocator: std.mem.Allocator) !Node {
        \\    return (
        \\        <div />
        \\    );
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "pub fn render(self: @This(), allocator: std.mem.Allocator) !Node");
    const count = std.mem.count(u8, result.code, "allocator: std.mem.Allocator");
    try std.testing.expectEqual(@as(usize, 2), count);
}


test "compiler: non-JSX return left untouched: return 42" {
    const src = "fn foo() u32 { return 42; }\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "return 42;");
}

test "compiler: non-JSX return left untouched: return foo()" {
    const src = "fn foo() u32 { return foo(); }\n";
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "return foo();");
}


test "compiler: string literal containing return ( not misidentified" {
    const src =
        \\const s = "return (<div />)";
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "\"return (<div />)\"");
}


test "compiler: comment containing return ( not misidentified" {
    const src =
        \\// return (<div />)
        \\const x = 1;
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "// return (<div />)");
}


test "compiler: multiple JSX blocks in one file" {
    const src =
        \\fn renderA() !Node {
        \\    return (
        \\        <div />
        \\    );
        \\}
        \\fn renderB() !Node {
        \\    return (
        \\        <span />
        \\    );
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try std.testing.expect(!result.has_errors);
    try expectContains(result.code, "out.appendSlice(allocator, \"<div>\")");
    try expectContains(result.code, "out.appendSlice(allocator, \"<span>\")");
}


test "compiler: parse error produces Node.empty placeholder" {
    const src =
        \\fn render() !Node {
        \\    return (
        \\        <div></span>
        \\    );
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try std.testing.expect(result.has_errors);
}


test "compiler: return (x < y) is not misidentified as JSX" {
    const src =
        \\fn compare(x: i32, y: i32) bool {
        \\    return (x < y);
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try std.testing.expect(!result.has_errors);
    try expectContains(result.code, "return (x < y)");
    try expectNotContains(result.code, "hAlloc(allocator");
}

test "compiler: return (<div />) is correctly identified as JSX" {
    const src =
        \\fn render() !Node {
        \\    return (
        \\        <div />
        \\    );
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try std.testing.expect(!result.has_errors);
    try expectContains(result.code, "out.appendSlice(allocator, \"<div>\")");
}

test "compiler: return (<>fragment</>) is correctly identified as JSX" {
    const src =
        \\fn render() !Node {
        \\    return (
        \\        <>hello</>
        \\    );
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try std.testing.expect(!result.has_errors);
    try expectContains(result.code, "out.appendSlice(allocator, \"hello\")");
}

test "compiler: noreturn_val is not misidentified" {
    const src =
        \\var noreturn_val: u32 = 0;
        \\fn foo() u32 { return noreturn_val; }
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "noreturn_val");
    try expectNotContains(result.code, "hAlloc(allocator");
}

test "compiler: return (x) with non-JSX content is not JSX" {
    const src =
        \\fn foo(x: u32) u32 {
        \\    return (x);
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "return (x)");
    try expectNotContains(result.code, "hAlloc(allocator");
}

test "compiler: return with comparison inside parens" {
    const src =
        \\fn check(a: i32, b: i32) bool {
        \\    return (a < b);
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "return (a < b)");
    try expectNotContains(result.code, "hAlloc(allocator");
}

test "compiler: multi-line string containing <tag> not misidentified" {
    const src =
        \\const template =
        \\    \\<div>hello</div>
        \\;
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectNotContains(result.code, "hAlloc(allocator");
}


test "compiler: emits #line comment before JSX codegen" {
    const src =
        \\const std = @import("std");
        \\const web = @import("web");
        \\
        \\pub fn render(self: @This()) !Node {
        \\    return (
        \\        <div />
        \\    );
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "// #line");
    try expectContains(result.code, "test.zsx");
}

test "compiler: #line comment maps to correct original line" {
    const src =
        \\const std = @import("std");
        \\const web = @import("web");
        \\
        \\pub fn render() !Node {
        \\    return (
        \\        <div />
        \\    );
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "// #line 6");
}

test "compiler: #line comment after JSX block resyncs" {
    const src =
        \\pub fn render() !Node {
        \\    return (
        \\        <div />
        \\    );
        \\}
        \\const after_jsx = true;
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "after_jsx");
    const count = std.mem.count(u8, result.code, "// #line");
    try std.testing.expect(count >= 2);
}

test "compiler: multiple JSX blocks each get #line comments" {
    const src =
        \\fn renderA() !Node {
        \\    return (
        \\        <div />
        \\    );
        \\}
        \\fn renderB() !Node {
        \\    return (
        \\        <span />
        \\    );
        \\}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    const count = std.mem.count(u8, result.code, "// #line");
    try std.testing.expect(count >= 4);
}


test "compiler: raw Zig code passes through" {
    const src =
        \\const MY_CONST = 42;
        \\fn helper() void {}
        \\
    ;
    const result = try compile(src);
    defer alloc.free(result.code);
    try expectContains(result.code, "const MY_CONST = 42;");
    try expectContains(result.code, "fn helper() void {}");
}
