const std = @import("std");

pub fn cleanDir(allocator: std.mem.Allocator, io: std.Io, dir_path: []const u8) !void {
    var dir = std.Io.Dir.openDir(.cwd(), io, dir_path, .{ .iterate = true }) catch |err| {
        if (err == error.FileNotFound) return;
        return err;
    };
    defer dir.close(io);

    var subdirs = std.ArrayList([]const u8).empty;
    defer {
        for (subdirs.items) |s| allocator.free(s);
        subdirs.deinit(allocator);
    }

    var to_delete = std.ArrayList([]const u8).empty;
    defer {
        for (to_delete.items) |s| allocator.free(s);
        to_delete.deinit(allocator);
    }

    var iter = dir.iterate();
    while (try iter.next(io)) |entry| {
        if (entry.kind == .directory) {
            try subdirs.append(allocator, try allocator.dupe(u8, entry.name));
            continue;
        }
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".zig")) continue;

        const content = dir.readFileAlloc(io, entry.name, allocator, @enumFromInt(100)) catch continue;
        defer allocator.free(content);
        if (std.mem.startsWith(u8, content, "// AUTO-GENERATED by planctl")) {
            try to_delete.append(allocator, try allocator.dupe(u8, entry.name));
        }
    }

    for (to_delete.items) |name| {
        dir.deleteFile(io, name) catch {};
        std.debug.print("planctl clean: removed {s}/{s}\n", .{ dir_path, name });
    }

    for (subdirs.items) |subdir_name| {
        const sub_path = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ dir_path, subdir_name });
        defer allocator.free(sub_path);
        try cleanDir(allocator, io, sub_path);
    }
}
