const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const yaml_dep = b.dependency("yaml", .{ .target = target, .optimize = optimize });
    const yaml_mod = yaml_dep.module("yaml");
    yaml_mod.link_libc = true;

    const utils_dep = b.dependency("utils", .{});
    const utils_mod = b.createModule(.{
        .root_source_file = utils_dep.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });

    const templates_manifest_src = generateTemplatesManifest(b);
    const templates_manifest_mod = b.createModule(.{
        .root_source_file = templates_manifest_src,
        .target = target,
        .optimize = optimize,
    });

    const raw_root = b.path("../..").getPath3(b, null).toString(b.allocator) catch @panic("OOM");
    const monorepo_root = std.fs.path.resolve(b.allocator, &.{raw_root}) catch @panic("OOM");
    const build_info_opts = b.addOptions();
    build_info_opts.addOption([]const u8, "monorepo_root", monorepo_root);
    const build_info_mod = build_info_opts.createModule();

    const planctl = b.addExecutable(.{
        .name = "planctl",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
            .imports = &.{
                .{ .name = "yaml", .module = yaml_mod },
                .{ .name = "utils", .module = utils_mod },
                .{ .name = "templates_manifest", .module = templates_manifest_mod },
                .{ .name = "build_info", .module = build_info_mod },
            },
        }),
    });
    b.installArtifact(planctl);

    const run_cmd = b.addRunArtifact(planctl);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }
    b.step("run", "Run planctl").dependOn(&run_cmd.step);

    const zsx_mod = b.createModule(.{
        .root_source_file = b.path("src/zsx/root.zig"),
        .target = target,
        .optimize = optimize,
    });

    const test_files = [_][]const u8{
        "src/tests/test_lexer.zig",
        "src/tests/test_parser.zig",
        "src/tests/test_compiler.zig",
    };

    const test_step = b.step("test", "Run compiler tests");
    for (test_files) |test_file| {
        const t = b.addTest(.{
            .root_module = b.createModule(.{
                .root_source_file = b.path(test_file),
                .target = target,
                .optimize = optimize,
                .imports = &.{
                    .{ .name = "zsx", .module = zsx_mod },
                },
            }),
        });
        test_step.dependOn(&b.addRunArtifact(t).step);
    }

    const deploy_config_mod = b.createModule(.{
        .root_source_file = b.path("src/deploy/config.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "yaml", .module = yaml_mod },
        },
    });
    const app_meta_mod = b.createModule(.{
        .root_source_file = b.path("src/deploy/app_meta.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "yaml", .module = yaml_mod },
        },
    });
    const yaml_test = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/tests/test_yaml_loader.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "yaml", .module = yaml_mod },
                .{ .name = "deploy_config", .module = deploy_config_mod },
                .{ .name = "app_meta", .module = app_meta_mod },
            },
        }),
    });
    test_step.dependOn(&b.addRunArtifact(yaml_test).step);
}

const TEMPLATE_NAMES = [_][]const u8{ "hda-mono", "hda-micro", "spa-mono", "spa-micro" };

fn generateTemplatesManifest(b: *std.Build) std.Build.LazyPath {
    const wf = b.addWriteFiles();

    var src: std.ArrayList(u8) = .empty;
    src.appendSlice(b.allocator,
        \\// AUTO-GENERATED by build.zig — do not edit.
        \\// Re-runs every `zig build`; walks `templates/<name>/` and bakes
        \\// each file into the planctl binary via `@embedFile`.
        \\
        \\pub const File = struct {
        \\    path:  []const u8,
        \\    bytes: []const u8,
        \\};
        \\pub const Template = struct {
        \\    name:  []const u8,
        \\    files: []const File,
        \\};
        \\
        \\
    ) catch @panic("OOM");

    const templates_root = b.path("templates").getPath3(b, null).toString(b.allocator) catch @panic("OOM");

    inline for (TEMPLATE_NAMES) |tname| {
        const tname_id = comptime kebabToSnake(tname);
        appendFmt(&src, b, "pub const {s}: Template = .{{\n    .name = \"{s}\",\n    .files = &.{{\n", .{ tname_id, tname });

        const tdir_abs = b.fmt("{s}/{s}", .{ templates_root, tname });
        emitTemplateEntries(b, wf, &src, tdir_abs, tname, "") catch |e| {
            std.debug.panic("template walk failed for {s}: {}", .{ tname, e });
        };

        src.appendSlice(b.allocator, "    },\n};\n\n") catch @panic("OOM");
    }

    appendFmt(&src, b,
        \\pub const all = [_]Template{{ {s} }};
        \\
        \\pub fn byName(name: []const u8) ?Template {{
        \\    const std = @import("std");
        \\    for (all) |t| if (std.mem.eql(u8, t.name, name)) return t;
        \\    return null;
        \\}}
        \\
    , .{comptime joinTemplateIds()});

    return wf.add("templates_manifest.zig", src.items);
}

fn emitTemplateEntries(b: *std.Build, wf: *std.Build.Step.WriteFile, src: *std.ArrayList(u8), dir_abs: []const u8, tname: []const u8, rel_prefix: []const u8) !void {
    const io = b.graph.io;
    var dir = try std.Io.Dir.openDirAbsolute(io, dir_abs, .{ .iterate = true });
    defer dir.close(io);

    var iter = dir.iterate();
    while (try iter.next(io)) |entry| {
        if (skipEntry(entry.name, rel_prefix)) continue;

        const child_rel = if (rel_prefix.len == 0)
            b.fmt("{s}", .{entry.name})
        else
            b.fmt("{s}/{s}", .{ rel_prefix, entry.name });
        const child_abs = b.fmt("{s}/{s}", .{ dir_abs, entry.name });

        switch (entry.kind) {
            .directory => try emitTemplateEntries(b, wf, src, child_abs, tname, child_rel),
            .file => {
                const staged_sub_path = b.fmt("{s}/{s}", .{ tname, child_rel });
                _ = wf.addCopyFile(b.path(b.fmt("templates/{s}/{s}", .{ tname, child_rel })), staged_sub_path);
                appendFmt(src, b, "        .{{ .path = \"{s}\", .bytes = @embedFile(\"{s}\") }},\n", .{ child_rel, staged_sub_path });
            },
            else => {},
        }
    }
}

fn appendFmt(buf: *std.ArrayList(u8), b: *std.Build, comptime fmt: []const u8, args: anytype) void {
    const line = b.fmt(fmt, args);
    buf.appendSlice(b.allocator, line) catch @panic("OOM");
}

fn skipEntry(name: []const u8, rel_prefix: []const u8) bool {
    const skip_dirs = [_][]const u8{
        "zig-out",      ".zig-cache",        "zig-pkg",
        "node_modules", "dist",              ".vscode",
        ".DS_Store",    "package-lock.json",
    };
    for (skip_dirs) |s| if (std.mem.eql(u8, name, s)) return true;

    if (std.mem.eql(u8, rel_prefix, "public") and std.mem.eql(u8, name, "assets")) {
        return true;
    }

    if (std.mem.endsWith(u8, rel_prefix, "/fragments") or std.mem.eql(u8, rel_prefix, "fragments")) {
        if (std.mem.endsWith(u8, name, ".zig")) return true;
    }
    return false;
}

fn kebabToSnake(comptime s: []const u8) []const u8 {
    comptime {
        var buf: [s.len]u8 = undefined;
        for (s, 0..) |c, i| buf[i] = if (c == '-') '_' else c;
        const out = buf;
        return &out;
    }
}

fn joinTemplateIds() []const u8 {
    comptime {
        var out: []const u8 = "";
        for (TEMPLATE_NAMES, 0..) |t, i| {
            if (i > 0) out = out ++ ", ";
            out = out ++ kebabToSnake(t);
        }
        return out;
    }
}
